[project]
name    = "alexandria"
version = "0.1.0-dev"
publish = false

[[bin]]
name = "alex"
test = false
doc  = false

[dependencies]
ring = "0.4"
byteorder = "0.5"

[dev-dependencies]
tempdir = "0.3"
